gText_Birch_Welcome::
	.string "Dear Applicant,\p"

	.string "We're pleased to let you know that\n"
	.string "you've been accepted as a Research\l"
	.string "Assistant this summer!\p"

	.string "Your application was certainly very\n"
	.string "interesting, and we can't wait to have\l"
	.string "you start working with us.\p"

	.string "We've made some interesting discoveries\n"
	.string "about the Pokémon in Twinland.\p"

	.string "As of recently, the Pokémon here have\n"
	.string "have been adapting into new forms.\p"

	.string "$"

gText_Birch_Pokemon::
	.string "…\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "And that is what you'll be helping us\n"
	.string "figure out!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "First, a little about yourself…$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "…and, what is your name?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}, right?$"

gText_Birch_YourePlayer::
	.string "Sounds great!\p"
	.string "That's all the information I need,\n"
	.string "for now.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "So, {PLAYER}.\p"

	.string "You'll be joining two other students to\n"
	.string "help out with my research.\p"

	.string "I'll be making accomodations for you to\n"
	.string "join us in TODO: Town.\p"

	.string "Have a safe journey!\p"
	.string "I hope to see you in my Pokémon Lab soon!\p"
	.string "$"
